language: node_js
sudo: false
jobs:
  include:
    - node_js: 8
      env:
        - DOWNGRADE=true
        - EXTRA=false
    - node_js: 12
      env:
        - DOWNGRADE=false
        - EXTRA=false
    - node_js: 14
      env:
        - DOWNGRADE=false
        - EXTRA=false
    - node_js: 16
      env:
        - DOWNGRADE=false
        - EXTRA=true
before_script:
  - "[ $DOWNGRADE = false ] || npm install rollup@1"
script:
  - "[ $EXTRA = false ] || npm run lint"
  - npm run prepare-tests
  - "[ $EXTRA = false ] || npm run build-umd"
  - "[ $EXTRA = false ] || npm run build-esm"
  - npm run test-node
notifications:
  email: false
env:
  global:
  - NPM_CONFIG_PROGRESS="false"
